version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ilude/${APP_NAME}-${DEPLOY_STAGE:-production}
    container_name: ${APP_NAME}
    restart: unless-stopped
    devices:
    - /dev/snd:/dev/snd
    env_file:
      - .env
    labels:
      - autoheal=true
      - joyride.host.name=${APP_NAME}.${APP_DOMAIN}
      - com.centurylinklabs.watchtower.enable=true